### ISSUE TITLE
Crash Nova 0.7.1

### ISSUE THREAD

**Issue by Eddi2015** [NovaMods/nova-renderer#139] opened 2018-07-18 07:26 UTC
Forge: 14.23.4.2739 (latest today)
-OS: Windows10
-no other mods
-first run
-using MultiMC
Crash log: https://privatebin.net/?50101f6e12995263#vqBRWu6Soj9epzg1yIHbcuPlbPrgIS39vDuP0PYpKcU=

**Comment by DethRaid** [comment] 2018-07-18 07:57
Duplicate of #138

**Closed by DethRaid** 2018-07-18 07:57 UTC
