### ISSUE TITLE
Nova crash 0.7.1 snapshot

### ISSUE THREAD

**Issue by JinTheDev** [NovaMods/nova-renderer#140] opened 2018-07-18 07:52 UTC
Log: https://hastebin.com/wegiwipici.rb
Specs:
-AMD Athlon II x4 630 CPU
-8 GB of RAM
-GTX 1050 TI

No other mods were loaded with Nova, and I have a x64 bit version of Windows 10.

**Comment by DethRaid** [comment] 2018-07-18 07:57
Duplicate of #138

**Closed by DethRaid** 2018-07-18 07:57 UTC
