### ISSUE TITLE
can you add higher render distance options to nova?

### ISSUE THREAD

**Issue by zakattac** [NovaMods/nova-renderer#70] opened 2017-09-04 17:52 UTC
please add 32 48 64 96 128 chunk render distance.

**Comment by DethRaid** [comment] 2017-09-07 19:29
Builderb0y is currently working on a method to accomplish this without giving the GPU absurd amounts of data

**Comment by cwfitzgerald** [comment] 2019-12-03 06:11
Duplicate of #80

**Closed by cwfitzgerald** 2019-12-03 06:11 UTC
Labels: enhancement
