### ISSUE TITLE
Under Windows not compiling (not helping MinGW)

### ISSUE THREAD

**Issue by acterhd** [NovaMods/nova-renderer#34] opened 2017-03-06 23:06 UTC
Look next posts

**Comment by tobiasschulz** [comment] 2017-03-06 23:11
Use Visual Studio.

**Comment by acterhd** [comment] 2017-03-06 23:12
I follow by instructions. Last (build) action fails.

**Comment by tobiasschulz** [comment] 2017-03-06 23:12
They are outdated

**Comment by acterhd** [comment] 2017-03-06 23:15
Strange - here is DEBUG only configuration.

**Comment by mdsitton** [comment] 2017-03-06 23:16
You likely have the wrong version of mingw-w64 installed you should have the seh w/ posix threads version installed. If you don't you will not have the c++11 threading library.

**Comment by mdsitton** [comment] 2017-03-06 23:18
You can check what version you have with `gcc --version` paste it here if you likr.

**Comment by Maximilian-Reuter** [comment] 2017-03-06 23:18
at least on windows it should be easier to simply use vs

**Comment by DethRaid** [comment] 2017-03-06 23:19
You mention DirectX. Nova does not use DirectX. Nova uses OpenGL 4.5.

You suggested moving to OpenGL ES 3.1. Why would I want to do that?

You definitely need a newer version of MinGW-w64 if you're going to use MinGW. Just install the latest version and you should be good to go

**Comment by acterhd** [comment] 2017-03-06 23:21
I tried CMAKE GUI with
`C:/dev/nova-renderer/src/main/cpp`
But Visual Studio **2017** gots errors (firstly going `-Wextra` error).

**Comment by DethRaid** [comment] 2017-03-06 23:22
Could you post the errors here?

**Comment by Maximilian-Reuter** [comment] 2017-03-06 23:22
some errors are to be expected since there are a lot of projects in there that don't build

**Comment by acterhd** [comment] 2017-03-06 23:24
Pastebin log
http://pastebin.com/TiR61akj

**Comment by tobiasschulz** [comment] 2017-03-06 23:25
It's really hard to read these logs because all the important log messages are in russian

**Comment by tobiasschulz** [comment] 2017-03-06 23:27
did you run the powershell script with the setup option?

**Comment by acterhd** [comment] 2017-03-06 23:29
Yes, runnned

**Comment by tobiasschulz** [comment] 2017-03-06 23:42
The build directory must have a path depth of 2 (relative to the repository directory)! 

Please just use the powershell script.

https://github.com/NovaMods/nova-renderer/blob/master/nova.ps1#L204

**Comment by acterhd** [comment] 2017-03-07 00:11
I tried again, but
1. Visual Studio anyways not compiling successfully. 
2. With GCC (MingW) library not running Minecraft

**Comment by DethRaid** [comment] 2017-03-07 00:12
Isn't it `-build -buildEnvironment=msvc`? Well, one of those should work.

If you only want to compile the native code, add the option `-nativeOnly`

**Comment by acterhd** [comment] 2017-03-07 00:15
Here is pastebin. 
http://pastebin.com/Je1EjQaJ

**Comment by acterhd** [comment] 2017-03-07 00:44
I also tried to edit CMAKE files and remove "-Wextra" flags, but some compilations gots errors with `m.lib`.

**Comment by DethRaid** [comment] 2017-03-07 00:47
It looks like you're running the tests. The tests are out of date (as are all great tests) and refer to code that doesn't exist any more (we changed how GUI geometry was handled in a pretty big way) and thus won't work.

Not sure how to disable them... the CMake file doesn't specify running the tests, so I'm not sure why they're getting run. Maybe VS 2017 runs them automatically?

**Comment by acterhd** [comment] 2017-03-07 00:57
VS compiling these tests anyways. With Mingw this does not doing.

**Comment by acterhd** [comment] 2017-03-07 01:09
Finally log from Intelij when running Minecraft. Despite of errors, `nova-renderer.dll` installed. But... 

```
"C:\Program Files\Java\jdk1.8.0_121\bin\java" -Djava.library.path=C:\dev\nova-renderer\jars\versions\1.10\1.10-natives -Didea.launcher.port=7536 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\dev\nova-renderer\build\classes\main;C:\dev\nova-renderer\build\resources\main;C:\dev\nova-renderer\jars\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar;C:\dev\nova-renderer\jars\libraries\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;C:\dev\nova-renderer\jars\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\dev\nova-renderer\jars\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\dev\nova-renderer\jars\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\dev\nova-renderer\jars\libraries\com\mojang\authlib\1.5.22\authlib-1.5.22.jar;C:\dev\nova-renderer\jars\libraries\com\mojang\netty\1.6\netty-1.6.jar;C:\dev\nova-renderer\jars\libraries\com\mojang\realms\1.9.1\realms-1.9.1.jar;C:\dev\nova-renderer\jars\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\dev\nova-renderer\jars\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\dev\nova-renderer\jars\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\dev\nova-renderer\jars\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\dev\nova-renderer\jars\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\dev\nova-renderer\jars\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\dev\nova-renderer\jars\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\dev\nova-renderer\jars\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\dev\nova-renderer\jars\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\dev\nova-renderer\jars\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar;C:\dev\nova-renderer\jars\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;C:\dev\nova-renderer\jars\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\dev\nova-renderer\jars\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\dev\nova-renderer\jars\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\dev\nova-renderer\jars\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\dev\nova-renderer\jars\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\dev\nova-renderer\jars\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\dev\nova-renderer\jars\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\dev\nova-renderer\jars\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\dev\nova-renderer\jars\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\dev\nova-renderer\jars\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\dev\nova-renderer\jars\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\dev\nova-renderer\jars\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\dev\nova-renderer\jars\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\dev\nova-renderer\jars\libraries\glm-1.0.1.jar;C:\dev\nova-renderer\jars\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain Start
2017-03-07 09:08:04,964 DEBUG Found Plugin Map at jar:file:/C:/dev/nova-renderer/jars/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar!/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat
2017-03-07 09:08:04,970 DEBUG Generated plugins in 0.007337801 seconds
2017-03-07 09:08:04,977 DEBUG Calling createLayout on class org.apache.logging.log4j.core.layout.PatternLayout for element PatternLayout with params(pattern="[%d{HH:mm:ss}] [%t/%level]: %msg%n", Configuration(C:\dev\nova-renderer\build\resources\main\log4j2.xml), null, charset="null", alwaysWriteExceptions="null")
2017-03-07 09:08:04,980 DEBUG Generated plugins in 0.002557958 seconds
2017-03-07 09:08:04,981 DEBUG Calling createAppender on class org.apache.logging.log4j.core.appender.ConsoleAppender for element Console with params(PatternLayout([%d{HH:mm:ss}] [%t/%level]: %msg%n), null, target="SYSTEM_OUT", name="SysOut", follow="null", ignoreExceptions="null")
2017-03-07 09:08:04,982 DEBUG Jansi is not installed, cannot find org.fusesource.jansi.WindowsAnsiOutputStream
2017-03-07 09:08:04,985 DEBUG Calling createLayout on class org.apache.logging.log4j.core.layout.PatternLayout for element PatternLayout with params(pattern="[%d{HH:mm:ss} %level]: %msg%n", Configuration(C:\dev\nova-renderer\build\resources\main\log4j2.xml), null, charset="null", alwaysWriteExceptions="null")
2017-03-07 09:08:04,986 DEBUG Calling createAppender on class com.mojang.util.QueueLogAppender for element Queue with params(name="ServerGuiConsole", ignoreExceptions="null", PatternLayout([%d{HH:mm:ss} %level]: %msg%n), null, target="null")
2017-03-07 09:08:04,987 DEBUG Calling createLayout on class org.apache.logging.log4j.core.layout.PatternLayout for element PatternLayout with params(pattern="[%d{HH:mm:ss}] [%t/%level]: %msg%n", Configuration(C:\dev\nova-renderer\build\resources\main\log4j2.xml), null, charset="null", alwaysWriteExceptions="null")
2017-03-07 09:08:04,987 DEBUG Calling createPolicy on class org.apache.logging.log4j.core.appender.rolling.TimeBasedTriggeringPolicy for element TimeBasedTriggeringPolicy with params(interval="null", modulate="null")
2017-03-07 09:08:04,988 DEBUG Calling createPolicy on class org.apache.logging.log4j.core.appender.rolling.OnStartupTriggeringPolicy for element OnStartupTriggeringPolicy
2017-03-07 09:08:04,989 DEBUG Calling createPolicy on class org.apache.logging.log4j.core.appender.rolling.CompositeTriggeringPolicy for element Policies with params(Policies={TimeBasedTriggeringPolicy, OnStartupTriggeringPolicy})
2017-03-07 09:08:04,990 DEBUG Calling createAppender on class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile with params(fileName="logs/latest.log", filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz", append="null", name="File", immediateFlush="null", Policies(CompositeTriggeringPolicy{TimeBasedTriggeringPolicy, OnStartupTriggeringPolicy}), null, PatternLayout([%d{HH:mm:ss}] [%t/%level]: %msg%n), null, ignoreExceptions="null", advertise="null", advertiseURI="null", Configuration(C:\dev\nova-renderer\build\resources\main\log4j2.xml))
2017-03-07 09:08:04,998 TRACE RandomAccessFile logs/latest.log seek to 214
2017-03-07 09:08:04,998 DEBUG Starting RollingRandomAccessFileManager logs/latest.log
2017-03-07 09:08:05,002 DEBUG Generated plugins in 0.002276533 seconds
2017-03-07 09:08:05,003 DEBUG Calling createAppenders on class org.apache.logging.log4j.core.config.plugins.AppendersPlugin for element Appenders with params(Appenders={SysOut, ServerGuiConsole, File})
2017-03-07 09:08:05,006 DEBUG Generated plugins in 0.002702615 seconds
2017-03-07 09:08:05,009 DEBUG Calling createFilter on class org.apache.logging.log4j.core.filter.MarkerFilter for element MarkerFilter with params(marker="NETWORK_PACKETS", onMatch="DENY", onMismatch="NEUTRAL")
2017-03-07 09:08:05,011 DEBUG Calling createFilters on class org.apache.logging.log4j.core.filter.CompositeFilter for element filters with params(Filters={NETWORK_PACKETS})
2017-03-07 09:08:05,011 DEBUG Calling createAppenderRef on class org.apache.logging.log4j.core.config.AppenderRef for element AppenderRef with params(ref="SysOut", level="null", null)
2017-03-07 09:08:05,012 DEBUG Calling createAppenderRef on class org.apache.logging.log4j.core.config.AppenderRef for element AppenderRef with params(ref="File", level="null", null)
2017-03-07 09:08:05,012 DEBUG Calling createAppenderRef on class org.apache.logging.log4j.core.config.AppenderRef for element AppenderRef with params(ref="ServerGuiConsole", level="null", null)
2017-03-07 09:08:05,013 DEBUG Calling createLogger on class org.apache.logging.log4j.core.config.LoggerConfig$RootLogger for element Root with params(additivity="null", level="info", includeLocation="null", AppenderRef={SysOut, File, ServerGuiConsole}, Properties={}, Configuration(C:\dev\nova-renderer\build\resources\main\log4j2.xml), filters({NETWORK_PACKETS}))
2017-03-07 09:08:05,014 DEBUG Calling createLoggers on class org.apache.logging.log4j.core.config.plugins.LoggersPlugin for element Loggers with params(Loggers={root})
2017-03-07 09:08:05,014 DEBUG Reconfiguration completed
[09:08:05] [Client thread/ERROR]: Can't find the resource index file: assets\indexes\1.8.json
[09:08:05] [Client thread/INFO]: Setting user: Player763
[09:08:05] [Client thread/INFO]: PID: 15660@DESKTOP-P1LRFK1
2017-03-07 09:08:05,539 INFO  [default] Loading config from config/config.json
ASSERTION FAILURE FROM EASYLOGGING++ (LINE: 2517) [(assertionPassed = base::utils::File::pathExists(configurationFile.c_str(), true))] WITH MESSAGE "Configuration file [config/logging.conf] does not exist!"
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffcac2cb998, pid=15660, tid=0x0000000000003a44
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x6b998]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\dev\nova-renderer\hs_err_pid15660.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 1
```

**Comment by acterhd** [comment] 2017-03-07 01:54
I don't know why...

**Comment by DethRaid** [comment] 2017-03-07 02:07
@tobiasschulz @Maximilian-Reuter didn't one of you add the dependency on the java glm for some reason? Did you set it up as a local file or something instead of going through MavenCentral or JCenter?

**Comment by DethRaid** [comment] 2017-03-07 02:39
Yes, you did do that, for reasons unknown. That's fixed now. @acterhd pull the latest and try running again, it has a higher chance of working now

**Comment by acterhd** [comment] 2017-03-07 03:05
I tried to run, created world, beginning.... WHAT?

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 07.03.17 11:03
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.client.renderer.RenderGlobal.setWorldAndLoadRenderers(RenderGlobal.java:474)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2478)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2428)
	at net.minecraft.client.Minecraft.launchIntegratedServer(Minecraft.java:2351)
	at net.minecraft.client.gui.GuiCreateWorld.actionPerformed(GuiCreateWorld.java:257)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:463)
	at net.minecraft.client.gui.GuiCreateWorld.mouseClicked(GuiCreateWorld.java:467)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:568)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:537)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1781)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.run(Minecraft.java:459)
	at net.minecraft.client.main.Main.main(Main.java:115)
	at Start.main(Start.java:9)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.setWorldAndLoadRenderers(RenderGlobal.java:474)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2478)
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:2428)
	at net.minecraft.client.Minecraft.launchIntegratedServer(Minecraft.java:2351)
	at net.minecraft.client.gui.GuiCreateWorld.actionPerformed(GuiCreateWorld.java:257)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:463)
	at net.minecraft.client.gui.GuiCreateWorld.mouseClicked(GuiCreateWorld.java:467)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:568)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:537)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1781)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.run(Minecraft.java:459)
	at net.minecraft.client.main.Main.main(Main.java:115)
	at Start.main(Start.java:9)

-- System Details --
Details:
	Minecraft Version: 1.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 425377304 bytes (405 MB) / 655360000 bytes (625 MB) up to 5475139584 bytes (5221 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: mcp
	LWJGL: 2.9.4
	OpenGL:  GL version , 
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

**Comment by acterhd** [comment] 2017-03-07 21:36
I'm interesting, why you have no gitter room?

**Comment by DethRaid** [comment] 2017-03-07 21:40
We have a Discord server. The link to join is in the README of this repo.

I haven't heard of Gitter until now. It looks pretty nice, but I don't see a reason to try and switch from Discord to Gitter.

**Comment by acterhd** [comment] 2017-03-08 04:11
Error of compiling "chunks" branch. 

```
Time Elapsed 00:00:15.86
:compileJava
C:\dev\nova-renderer\src\main\java\com\continuum\nova\NovaRenderer.java:113: error: cannot find symbol
        guiAtlas.createWhiteTexture(WHITE_TEXTURE_GUI_LOCATION);
                ^
  symbol:   method createWhiteTexture(ResourceLocation)
  location: variable guiAtlas of type TextureMap
C:\dev\nova-renderer\src\main\java\com\continuum\nova\NovaRenderer.java:130: error: cannot find symbol
        Optional<TextureAtlasSprite> whiteImage = atlas.getWhiteImage();
                                                       ^
  symbol:   method getWhiteImage()
  location: variable atlas of type TextureMap
C:\dev\nova-renderer\src\main\java\com\continuum\nova\NovaRenderer.java:131: error: cannot find symbol
        whiteImage.ifPresent(image -> spriteLocations.put(image.getLocation(), image));
                                                               ^
  symbol:   method getLocation()
  location: variable image of type TextureAtlasSprite
C:\dev\nova-renderer\src\main\java\com\continuum\nova\NovaRenderer.java:133: error: cannot find symbol
        NovaNative.mc_atlas_texture atlasTexture = getFullImage(atlas.getWidth(), atlas.getHeight(), spriteLocations.values());
                                                                     ^
  symbol:   method getWidth()
  location: variable atlas of type TextureMap
C:\dev\nova-renderer\src\main\java\com\continuum\nova\NovaRenderer.java:133: error: cannot find symbol
        NovaNative.mc_atlas_texture atlasTexture = getFullImage(atlas.getWidth(), atlas.getHeight(), spriteLocations.values());
                                                                                       ^
  symbol:   method getHeight()
  location: variable atlas of type TextureMap
C:\dev\nova-renderer\src\main\java\com\continuum\nova\utils\SettingsCommandBuilder.java:16: error: cannot find symbol
        settings.fog_color_red = mc.entityRenderer.getFogColorRed();
                                                  ^
  symbol:   method getFogColorRed()
  location: variable entityRenderer of type EntityRenderer
C:\dev\nova-renderer\src\main\java\com\continuum\nova\utils\SettingsCommandBuilder.java:17: error: cannot find symbol
        settings.fog_color_green = mc.entityRenderer.getFogColorGreen();
                                                    ^
  symbol:   method getFogColorGreen()
  location: variable entityRenderer of type EntityRenderer
C:\dev\nova-renderer\src\main\java\com\continuum\nova\utils\SettingsCommandBuilder.java:18: error: cannot find symbol
        settings.fog_color_blue = mc.entityRenderer.getFogColorBlue();
                                                   ^
  symbol:   method getFogColorBlue()
  location: variable entityRenderer of type EntityRenderer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.482 secs
New-NovaCode : Gradle invocation failed, aborting
At C:\dev\nova-renderer\nova.ps1:319 char:5
+     New-NovaCode -buildEnvironment $buildEnvironment
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-NovaCode

False
```

**Comment by DethRaid** [comment] 2017-03-08 04:23
Yeah... Yeah, it won't work. Just remembered why. Sorry it took so long.

Nova makes a number of modifications to the Minecraft code. Ideally we could commit the Minecraft code with our modifications to a public repository somewhere and you guys could download from that, no problemo. Minecraft's licensing doesn't allow that, however, so we actually have a private repo with the Minecraft source code with our modifications. This works for Nova's developers: we can download the Minecraft source code along with Nova and party.

Of course, there's people other than developers who want to use Nova (even though it's so far from being feature complete), so we had to figure out something for them. The solution we settled on is distributing patch files which modify the Minecraft code to do what we want. You'll find the latest patch file in the `src/main/resources` folder somewhere. The patch file works great... when we generate them. We don't always generate them. Possibly I could do something to generate a patch file whenever we make a new commit to our version of the Minecraft code, but to be honest I don't want to spend a lot of time making Nova accessible to non-developers. There's two main reasons for this: every bit of effort spent on that is effort that isn't spent on delivering features, and I don't really want people to use Nova yet. Nova (in my opinion) doesn't do enough to be useful to a wide variety of people, and I'd much rather spend my time fixing that.

So yeah. Branches other than `master` aren't expected to work. Sorry about that, should have remembered sooner.

**Closed by DethRaid** 2017-03-08 04:23 UTC

**Comment by acterhd** [comment] 2017-03-08 04:25
Why you closed issue?

**Comment by DethRaid** [comment] 2017-03-08 15:22
I closed the issue because the cause of your problem is that the patch file which applies our changes to the Minecraft source code is not up to date, and there are no plans to bring it up to date before significant progress has been made on chunk rendering.
